//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkademiPlus_Transportation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReference
    {
        public int ReferenceID { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceContent { get; set; }
        public string ReferenceImage { get; set; }
        public string ReferenceSubtitle { get; set; }
    }
}
